tasks/urls.py
from django.contrib import admin
from django.urls import path
from todo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.task, name='task'),
]

todo/models.py
from django.db import models


class Task (models.Model):

    title = models.CharField(max_length=100)
    description = models.TextField()
    date_task = models.DateField(auto_now_add=True)
    time_task = models.TimeField(auto_now_add=True)
    deadline_task = models.DateField()
    STATUS_CHOICES = [
        ('01', 'Ожидает выполнения'),
        ('02', 'В процессе выполнения'),
        ('03', 'Выполнена'),

    ]
    name_status = models.CharField(choices=STATUS_CHOICES, max_length=100, verbose_name="Статус")
    PRIORITY_CHOICES = [
        ('01', 'Низкий'),
        ('02', 'Средний'),
        ('03', 'Высокий'),

    ]
    name_priority = models.CharField(choices=PRIORITY_CHOICES, max_length=100,verbose_name="Приоритет")

    def __str__(self):
        return self.name_priority

    def __str__(self):
        return self.name_status

    def __str__(self):
        return self.title

todo/views.py
from django.shortcuts import render
from .models import Task

def task (request):
    tasks = Task.objects.order_by('date_task')
    return render(request, 'tasks.html', context={"tasks": tasks})

templates/tasks.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tasks</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>
{% for task in tasks %}
<ul>
    <li>
<p><b>{{ task.title}}</b></p>

{% if task.get_name_priority_display == 'Низкий' %}
   <p class="priority1">{{ task.get_name_priority_display }}</p>
{% elif task.get_name_priority_display == 'Средний' %}
    <p class="priority2">{{ task.get_name_priority_display }}</p>
{% else %}
    <p class="priority3">{{ task.get_name_priority_display }}</p>
{% endif %}

<p>{{ task.status }}</p>
<p> Создана: {{ task.date_task }} {{ task.time_task }}</p>
<p> Сделать до: {{ task.deadline_task }}</p>
<p>{{ task.description }}</p>
    </li>
    </br>
</ul>
{% endfor %}

</body>
</html>